org: syamniravilpuzha
app: node-aws-starter
service: node-aws-starter

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'